package uk.hmcts.zephyr.automation.cypress;

import lombok.SneakyThrows;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by AI based on the need to add tags to Cypress tests by modifying the source code.
 * This class provides a method to add a tag to a Cypress test by parsing the test file,
 * finding the relevant "it" call, and updating its options object to include the new tag.
 */
@SuppressWarnings({
    "LineLength",
    "MultipleVariableDeclarations",
    "LineLength"
})
public class CypressTagger {


    @SneakyThrows
    public static void addTagToCypressTest(String filePath, String targetTitle, String newTag) {
        String input = Files.readString(Path.of(filePath), StandardCharsets.UTF_8);
        String output = addTagToCypressTestInContent(input, targetTitle, newTag);
        Files.writeString(Path.of(filePath), output, StandardCharsets.UTF_8);
    }

    static String addTagToCypressTestInContent(String input, String targetTitle, String newTag) {
        StringBuilder out = new StringBuilder(input.length());
        int i = 0;

        while (i < input.length()) {
            int itPos = indexOfItCall(input, i);
            if (itPos < 0) {
                out.append(input.substring(i));
                break;
            }

            // Copy everything up to the it(
            out.append(input, i, itPos);

            // Parse full it(...) call
            ParseCallResult call = parseCall(input, itPos, "it");
            if (!call.ok) {
                // If parsing fails, just copy one char and continue to avoid infinite loop
                out.append(input.charAt(itPos));
                i = itPos + 1;
                continue;
            }

            String callText = input.substring(call.startIndex, call.endIndexExclusive);
            String updatedCallText = maybeUpdateItCall(callText, targetTitle, newTag);

            out.append(updatedCallText);
            i = call.endIndexExclusive;
        }

        return out.toString();
    }

    // Finds "it" followed by optional whitespace then '(' (not part of a longer identifier).
    static int indexOfItCall(String s, int from) {
        int n = s.length();
        for (int i = from; i < n - 2; i++) {
            char c = s.charAt(i);
            if (c != 'i') {
                continue;
            }
            if (i + 1 >= n || s.charAt(i + 1) != 't') {
                continue;
            }

            // Ensure not part of a larger identifier: boundary before 'i'
            if (i > 0 && isIdentChar(s.charAt(i - 1))) {
                continue;
            }

            int j = i + 2;
            while (j < n && Character.isWhitespace(s.charAt(j))) {
                j++;
            }
            if (j < n && s.charAt(j) == '(') {
                return i;
            }
        }
        return -1;
    }

    static boolean isIdentChar(char c) {
        return Character.isLetterOrDigit(c) || c == '_' || c == '$';
    }

    static class ParseCallResult {
        final boolean ok;
        final int startIndex;          // start of "it"
        final int endIndexExclusive;   // end after matching ')'

        ParseCallResult(boolean ok, int startIndex, int endIndexExclusive) {
            this.ok = ok;
            this.startIndex = startIndex;
            this.endIndexExclusive = endIndexExclusive;
        }
    }

    // Parses "it( ... )" with balanced parentheses, respecting strings and comments.
    static ParseCallResult parseCall(String s, int start, String fnName) {
        int n = s.length();
        int i = start + fnName.length();
        while (i < n && Character.isWhitespace(s.charAt(i))) {
            i++;
        }
        if (i >= n || s.charAt(i) != '(') {
            return new ParseCallResult(false, start, start + 1);
        }

        int parenDepth = 0;
        boolean inSingle = false, inDouble = false, inTemplate = false;
        boolean inLineComment = false, inBlockComment = false;

        for (; i < n; i++) {
            char c = s.charAt(i);
            char next = (i + 1 < n) ? s.charAt(i + 1) : '\0';

            if (inLineComment) {
                if (c == '\n') {
                    inLineComment = false;
                }
                continue;
            }
            if (inBlockComment) {
                if (c == '*' && next == '/') {
                    inBlockComment = false;
                    i++;
                }
                continue;
            }

            // Start comments (only when not in strings)
            if (!inSingle && !inDouble && !inTemplate) {
                if (c == '/' && next == '/') {
                    inLineComment = true;
                    i++;
                    continue;
                }
                if (c == '/' && next == '*') {
                    inBlockComment = true;
                    i++;
                    continue;
                }
            }

            // Handle string toggles with escapes
            if (inSingle) {
                if (c == '\\') {
                    i++;
                    continue;
                } // skip escaped char
                if (c == '\'') {
                    inSingle = false;
                }
                continue;
            }
            if (inDouble) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '"') {
                    inDouble = false;
                }
                continue;
            }
            if (inTemplate) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '`') {
                    inTemplate = false;
                }
                continue;
            }

            // Not in a string/comment:
            if (c == '\'') {
                inSingle = true;
                continue;
            }
            if (c == '"') {
                inDouble = true;
                continue;
            }
            if (c == '`') {
                inTemplate = true;
                continue;
            }

            if (c == '(') {
                parenDepth++;
            }
            if (c == ')') {
                parenDepth--;
                if (parenDepth == 0) {
                    // include the closing ')'
                    return new ParseCallResult(true, start, i + 1);
                }
            }
        }

        return new ParseCallResult(false, start, start + 1);
    }

    static String maybeUpdateItCall(String callText, String targetTitle, String newTag) {
        // callText is like: it( ... )
        int openParen = callText.indexOf('(');
        int closeParen = callText.lastIndexOf(')');
        if (openParen < 0 || closeParen < 0 || closeParen <= openParen) {
            return callText;
        }

        String inside = callText.substring(openParen + 1, closeParen);
        List<String> args = splitTopLevelArgs(inside);

        if (args.isEmpty()) {
            return callText;
        }

        String titleExpr = args.getFirst().trim();
        String resolvedTitle = resolveSingleQuotedConcat(titleExpr);
        if (resolvedTitle == null) {
            return callText;
        }

        if (!resolvedTitle.equals(targetTitle)) {
            return callText;
        }

        // Ensure we have an options object in arg1. If missing, we could insert one, but your example has it.
        if (args.size() < 2) {
            return callText;
        }

        String options = args.get(1);
        String updatedOptions = updateTagsInOptionsObject(options, newTag);

        args.set(1, updatedOptions);

        // Rebuild inside (preserve original spacing around commas loosely)
        String rebuiltInside = String.join(", ", args);
        return callText.substring(0, openParen + 1) + rebuiltInside + callText.substring(closeParen);
    }

    // Splits arguments by commas at top level, respecting nested braces/parens/brackets and strings/comments.
    static List<String> splitTopLevelArgs(String s) {
        List<String> parts = new ArrayList<>();
        int start = 0;

        int paren = 0, brace = 0, bracket = 0;
        boolean inSingle = false, inDouble = false, inTemplate = false;
        boolean inLineComment = false, inBlockComment = false;

        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            char next = (i + 1 < s.length()) ? s.charAt(i + 1) : '\0';

            if (inLineComment) {
                if (c == '\n') {
                    inLineComment = false;
                }
                continue;
            }
            if (inBlockComment) {
                if (c == '*' && next == '/') {
                    inBlockComment = false;
                    i++;
                }
                continue;
            }

            if (!inSingle && !inDouble && !inTemplate) {
                if (c == '/' && next == '/') {
                    inLineComment = true;
                    i++;
                    continue;
                }
                if (c == '/' && next == '*') {
                    inBlockComment = true;
                    i++;
                    continue;
                }
            }

            if (inSingle) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '\'') {
                    inSingle = false;
                }
                continue;
            }
            if (inDouble) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '"') {
                    inDouble = false;
                }
                continue;
            }
            if (inTemplate) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '`') {
                    inTemplate = false;
                }
                continue;
            }

            if (c == '\'') {
                inSingle = true;
                continue;
            }
            if (c == '"') {
                inDouble = true;
                continue;
            }
            if (c == '`') {
                inTemplate = true;
                continue;
            }

            if (c == '(') {
                paren++;
            } else if (c == ')') {
                paren--;
            } else if (c == '{') {
                brace++;
            } else if (c == '}') {
                brace--;
            } else if (c == '[') {
                bracket++;
            } else if (c == ']') {
                bracket--;
            }

            if (c == ',' && paren == 0 && brace == 0 && bracket == 0) {
                parts.add(s.substring(start, i).trim());
                start = i + 1;
            }
        }

        String tail = s.substring(start).trim();
        if (!tail.isEmpty()) {
            parts.add(tail);
        }
        return parts;
    }

    // Resolves: 'a' + 'b' + 'c' (possibly across whitespace/newlines) into "abc".
    // Returns null if expression doesn't look like that pattern.
    static String resolveSingleQuotedConcat(String expr) {
        int i = 0;
        StringBuilder sb = new StringBuilder();
        boolean sawAny = false;

        while (true) {
            i = skipWs(expr, i);
            if (i >= expr.length() || expr.charAt(i) != '\'') {
                return sawAny ? sb.toString() : null;
            }

            StringParseResult lit = parseSingleQuotedLiteral(expr, i);
            if (!lit.ok) {
                return null;
            }
            sb.append(lit.value);
            sawAny = true;
            i = lit.nextIndex;

            i = skipWs(expr, i);
            if (i < expr.length() && (expr.charAt(i) == '+' || expr.charAt(i) == '&')) {
                i++; // consume operator, continue expecting next string
                continue;
            }

            // Done (no operator)
            i = skipWs(expr, i);
            if (i == expr.length()) {
                return sb.toString();
            }

            // Extra tokens => not a pure concat expression
            return null;
        }
    }

    static int skipWs(String s, int i) {
        while (i < s.length() && Character.isWhitespace(s.charAt(i))) {
            i++;
        }
        return i;
    }

    static class StringParseResult {
        final boolean ok;
        final String value;
        final int nextIndex;

        StringParseResult(boolean ok, String value, int nextIndex) {
            this.ok = ok;
            this.value = value;
            this.nextIndex = nextIndex;
        }
    }

    static StringParseResult parseSingleQuotedLiteral(String s, int start) {
        if (start >= s.length() || s.charAt(start) != '\'') {
            return new StringParseResult(false, "", start);
        }
        StringBuilder sb = new StringBuilder();
        int i = start + 1;
        while (i < s.length()) {
            char c = s.charAt(i);
            if (c == '\\') {
                if (i + 1 >= s.length()) {
                    return new StringParseResult(false, "", i);
                }
                char next = s.charAt(i + 1);
                sb.append(next); // unescape \' -> ' etc.
                i += 2;
                continue;
            }
            if (c == '\'') {
                return new StringParseResult(true, sb.toString(), i + 1);
            }
            sb.append(c);
            i++;
        }
        return new StringParseResult(false, "", i);
    }

    // Updates { tags: [...] } inside the options object string. Keeps it simple and local.
    static String updateTagsInOptionsObject(String options, String newTag) {
        // We only attempt edits if arg looks like an object literal.
        int firstBrace = options.indexOf('{');
        int lastBrace = options.lastIndexOf('}');
        if (firstBrace < 0 || lastBrace < 0 || lastBrace <= firstBrace) {
            return options;
        }

        String before = options.substring(0, firstBrace + 1);
        String body = options.substring(firstBrace + 1, lastBrace);
        String after = options.substring(lastBrace);

        // Look for tags: [ ... ]
        int tagsIdx = indexOfTopLevelKey(body, "tags");
        if (tagsIdx >= 0) {
            // Find the bracketed array after "tags:"
            int colon = body.indexOf(':', tagsIdx);
            if (colon < 0) {
                return options;
            }

            int j = colon + 1;
            while (j < body.length() && Character.isWhitespace(body.charAt(j))) {
                j++;
            }
            if (j >= body.length() || body.charAt(j) != '[') {
                return options;
            }

            int arrayStart = j;
            int arrayEnd = findMatchingBracket(body, arrayStart, '[', ']');
            if (arrayEnd < 0) {
                return options;
            }

            String arrayInner = body.substring(arrayStart + 1, arrayEnd).trim();

            // Check if already present as a single-quoted tag.
            String needle = "'" + newTag.replace("'", "\\'") + "'";
            if (containsTag(arrayInner, newTag)) {
                return options; // no dupes
            }

            String updatedInner;
            if (arrayInner.isEmpty()) {
                updatedInner = needle;
            } else {
                updatedInner = arrayInner + ", " + needle;
            }

            String newBody = body.substring(0, arrayStart + 1)
                + updatedInner
                + body.substring(arrayEnd);

            return before + newBody + after;
        } else {
            // No tags property: insert one near the start of object body
            String insert = " tags: ['" + newTag.replace("'", "\\'") + "']";
            String trimmed = body.trim();
            if (trimmed.isEmpty()) {
                return before + insert + " " + after;
            }
            // Add comma if needed
            String bodyLeading = body;
            if (trimmed.startsWith(",")) {
                return before + insert + body + after;
            }
            // Insert at beginning with trailing comma
            return before + insert + ", " + body.trim() + after;
        }
    }

    // Finds a key at top-level in an object body (not inside nested braces/strings).
    static int indexOfTopLevelKey(String body, String key) {
        int brace = 0, bracket = 0, paren = 0;
        boolean inSingle = false, inDouble = false, inTemplate = false;
        boolean inLineComment = false, inBlockComment = false;

        for (int i = 0; i < body.length(); i++) {
            char c = body.charAt(i);
            char next = (i + 1 < body.length()) ? body.charAt(i + 1) : '\0';

            if (inLineComment) {
                if (c == '\n') {
                    inLineComment = false;
                }
                continue;
            }
            if (inBlockComment) {
                if (c == '*' && next == '/') {
                    inBlockComment = false;
                    i++;
                }
                continue;
            }

            if (!inSingle && !inDouble && !inTemplate) {
                if (c == '/' && next == '/') {
                    inLineComment = true;
                    i++;
                    continue;
                }
                if (c == '/' && next == '*') {
                    inBlockComment = true;
                    i++;
                    continue;
                }
            }

            if (inSingle) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '\'') {
                    inSingle = false;
                }
                continue;
            }
            if (inDouble) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '"') {
                    inDouble = false;
                }
                continue;
            }
            if (inTemplate) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '`') {
                    inTemplate = false;
                }
                continue;
            }

            if (c == '\'') {
                inSingle = true;
                continue;
            }
            if (c == '"') {
                inDouble = true;
                continue;
            }
            if (c == '`') {
                inTemplate = true;
                continue;
            }

            if (c == '{') {
                brace++;
            } else if (c == '}') {
                brace--;
            } else if (c == '[') {
                bracket++;
            } else if (c == ']') {
                bracket--;
            } else if (c == '(') {
                paren++;
            } else if (c == ')') {
                paren--;
            }

            if (brace == 0 && bracket == 0 && paren == 0) {
                // crude but effective: look for "tags" as an identifier boundary
                if (matchesKeyAt(body, i, key)) {
                    return i;
                }
            }
        }
        return -1;
    }

    static boolean matchesKeyAt(String s, int i, String key) {
        int n = s.length();
        if (i + key.length() > n) {
            return false;
        }
        if (!s.regionMatches(i, key, 0, key.length())) {
            return false;
        }

        char before = (i > 0) ? s.charAt(i - 1) : '\0';
        char after = (i + key.length() < n) ? s.charAt(i + key.length()) : '\0';

        if (isIdentChar(before)) {
            return false;
        }
        if (isIdentChar(after)) {
            return false;
        }
        return true;
    }

    static int findMatchingBracket(String s, int openIdx, char open, char close) {
        int depth = 0;
        boolean inSingle = false, inDouble = false, inTemplate = false;

        for (int i = openIdx; i < s.length(); i++) {
            char c = s.charAt(i);

            if (inSingle) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '\'') {
                    inSingle = false;
                }
                continue;
            }
            if (inDouble) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '"') {
                    inDouble = false;
                }
                continue;
            }
            if (inTemplate) {
                if (c == '\\') {
                    i++;
                    continue;
                }
                if (c == '`') {
                    inTemplate = false;
                }
                continue;
            }

            if (c == '\'') {
                inSingle = true;
                continue;
            }
            if (c == '"') {
                inDouble = true;
                continue;
            }
            if (c == '`') {
                inTemplate = true;
                continue;
            }

            if (c == open) {
                depth++;
            } else if (c == close) {
                depth--;
                if (depth == 0) {
                    return i;
                }
            }
        }
        return -1;
    }

    static boolean containsTag(String arrayInner, String tag) {
        // Very simple membership check: look for 'TAG' with optional whitespace around commas.
        // If you want to support double quotes too, expand this.
        String needle = "'" + tag + "'";
        return arrayInner.contains(needle);
    }
}

